id: winservices-integration-docs
displayName: Windows services
description: |
  With our Windows services integration you can monitor service availability, performance and events. See your data from both native Windows services and third-party services.
install:
  primary:
    link:
      url: https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/windows-services-integration/
icon: logo.svg
