id: redis-enterprise
displayName: Redis Enterprise
description: |
  With this integration, you can get deep insight into the Redis Enterprise Software. You can see detailed cluster, database, and Active-Active metrics.
icon: logo.png
install:
  primary:
    link:
      url: https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/redis/redis-enterprise-integration/
keywords:
  - newrelic partner
  - devops
  - redis enterprise
  - redis
  - featured
  - cluster
  - database
  - active
categoryTerms:
  - newrelic partner
