id: sendmail
displayName: Sendmail
description: |
  Use our infrastructure agent and Flex configuration to export Sendmail data to New Relic.
install:
  primary:
    link:
      url: https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/sendmail-monitoring-integration
icon: logo.png
