id: redpanda
displayName: Redpanda
description: |
  With our infrastructure agent and Prometheus integration, you can track your Redpanda data. See your Redpanda scheduling groups, service errors, and uptime.
install:
  primary:
    link:
      url: https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/redpanda-integration/
icon: logo.png
