id: github-repo
displayName: GitHub Repository Monitoring
description: |
  Monitor your GitHub or GitHub Enterprise repositories by adding your New Relic Log API endpoint as a webhook in GitHub.
install:
  primary:
    link:
      url: https://docs.newrelic.com/docs/logs/log-api/introduction-log-api/
icon: logo.png
